<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    /**
     * Convert a validation exception into a JSON response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Validation\ValidationException  $exception
     * @return \Illuminate\Http\JsonResponse
     */
    protected function invalidJson($request, ValidationException $exception)
    {
        $errors = $this->getErrors($exception);

        return response()->json([
            'status' => "Validation errors",
            'errors' => $errors,
        ], $exception->status);
    }

    private function getErrors(ValidationException $e)
    {
        $errors = $e->validator->errors()->getMessages();

        $transformed = [];

        foreach ($errors as $field => $message) {
            $transformed[$field] = [
                'message' => $message[0]
            ];
        }

        return $transformed;
    }
}
